config/routes.rb
Rails.application.routes.draw do
  resources :items
  root 'items#index'
  #root 'pages#about'
  get 'about', to: 'pages#about'
  get 'newitem', to: 'items#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :thumbnail
    has_one_attached :image


    def optimized_image(image, x, y)
        return image.variant(resize_to_fill: [x, y]).processed
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :quantity, :price, :description, :thumbnail, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.label :title, class:"form-control" %>
    <%= f.input :title, class:"form-control string", required: true, label: false  %>
    <br>
    <%= f.label :quantity, class:"form-control" %>
    <%= f.input :quantity, required: true, label: false %>
    <br>
    <%= f.label :price, class:"form-control" %>
    <%= f.input :price, required: true, label: false %>
    <br>
    <%= f.label :description, class:"form-control" %>
    <%= f.input :description, required: true, label: false %>
    <br>
    <%= f.label :image, class:"form-control" %>
    <%= f.file_field :image, required: true %>
  </div>

  <br><br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding-top: 5px;
  padding-bottom: 5px;
  padding-left: 10px;
  padding-right: 10px;
}
</style>
</head>

<p id="notice"><%= notice %></p>

<h1>Complete Inventory</h1>

<table>
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Title</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><div style="width:150px; height: 150px;">
          <%= image_tag(item.image, style:'width:100%; height:100%') %>
        </div>
        </td>
        <td><%= item.title %></td>
        <td><%= item.quantity %></td>
        <td><%= item.price %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'View', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>Create New Item</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Price: $</strong>
  <%= @item.price %>
</p>


<div style="width:300px; height: 300px; overflow-y:hidden">
  <%= image_tag(@item.image, style:'width:100%; height:100%') %>
</div>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= about_path %>">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= root_path %>">View Inventory</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= newitem_path %>">Add Item</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyChallenge2022</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<br><br>

<div class="h-100 p-5 text-white bg-dark rounded-3">
<h2>About the project</h2>
<p>This is a project based on the guidelines on the  <a href="https://docs.google.com/document/d/1z9LZ_kZBUbg-O2MhZVVSqTmvDko5IJWHtuFmIu_Xg1A/edit">Shopify 2022 Intern application</a>. 
It is a basic CRUD application which replicates an inventory management system. You are able to create inventory items, edit, 
view, and delete each of them, as well as view the entire inventory at once. This can be done by using the links in the top
navbar or with the links alongside each item in the group view page. This project was creating using Ruby on Rails, with active 
storage for the image component.

<br><br>The feature I chose to include from the provided list was <i>allowing image uploads and storing of the image with 
generated thumbnails</i>. Thank you for taking the time to look at my project and for the consideration of my application.
If you have any questions or advice to improve, my email is ferrucciosisti@gmail.com
<br><br><br><br><br><br><br><br><br>
</p>
</div>